Update Generate Domain List.yml
Signed-off-by: REIJI007 <miyajimareji007@gmail.com>

diff --git a/.github/workflows/Generate Domain List.yml b/.github/workflows/Generate Domain List.yml
--- a/.github/workflows/Generate Domain List.yml
+++ b/.github/workflows/Generate Domain List.yml
@@ -105,10 +105,22 @@ jobs:
           done
           
           if [ "$success" = true ]; then
-              # 强制推送更改
-              git push --force origin main
+              attempt=0
+              success=false
+              while [ $attempt -lt $max_attempts ]; do
+                  git push origin main && success=true && break
+                  attempt=$((attempt + 1))
+                  echo "Push failed, retrying in 10 seconds... (Attempt $attempt of $max_attempts)"
+                  sleep 10
+              done
+              
+              if [ "$success" = false ]; then
+                  echo "Failed to push after $max_attempts attempts."
+                  exit 1
+              fi
           else
               echo "Failed to commit after $max_attempts attempts."
+              exit 1
           fi
         env:
           GITHUB_TOKEN: ${{ secrets.TOKEN }}
